version: '3.4'

services: 

  bot-slack:  
    image: 280035946601.dkr.ecr.us-east-1.amazonaws.com/bot-slack  
    container_name: bot-slack
    environment:
      - CLIENT_NAME=${CLIENT_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} 
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - VERIFICATION_TOKEN=${VERIFICATION_TOKEN}
    networks: 
      - teampulse
    restart: always

  analytics:  
    image: 280035946601.dkr.ecr.us-east-1.amazonaws.com/analytics
    container_name: analytics
    environment:
      - CLIENT_NAME=${CLIENT_NAME}
      - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} 
    networks: 
      - teampulse
    restart: always

  client:
    image: 280035946601.dkr.ecr.us-east-1.amazonaws.com/client
    container_name: client
    environment:
      - CLIENT_NAME=${CLIENT_NAME}
      - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} 
    ports:
      - "80:80"
    networks: 
      - teampulse
    restart: always
    depends_on: 
      - server

  server:  
    image: 280035946601.dkr.ecr.us-east-1.amazonaws.com/server  
    container_name: server
    environment: 
      - GSHEETS_MESSAGES_BY_DAY=${GSHEETS_MESSAGES_BY_DAY}
      - GSHEETS_MESSAGES_LAST_7_DAYS=${GSHEETS_MESSAGES_LAST_7_DAYS}
      - GSHEETS_MESSAGES_BY_WEEK=${GSHEETS_MESSAGES_BY_WEEK}
      - GSHEETS_MESSAGES_BY_CHANNEL=${GSHEETS_MESSAGES_BY_CHANNEL}
      - GSHEETS_NOTE_GLOBAL_POLARITY=${GSHEETS_NOTE_GLOBAL_POLARITY}
      - GSHEETS_TOP_5_REACTIONS=${GSHEETS_TOP_5_REACTIONS}
      - GSHEETS_TOP_5_EMOJIS=${GSHEETS_TOP_5_EMOJIS}
      - GSHEETS_TOP_10_WORDS=${GSHEETS_TOP_10_WORDS}
      - GSHEETS_TOP_10_POSITIVE=${GSHEETS_TOP_10_POSITIVE}
      - GSHEETS_TOP_10_NEGATIVE=${GSHEETS_TOP_10_NEGATIVE}
      - GSHEETS_INDICES_BIENESTAR=${GSHEETS_INDICES_BIENESTAR}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - TYPEFORM_TOKEN=${TYPEFORM_TOKEN}
      - URL_CLIENT=${URL_CLIENT}
      - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
      - URL_ESTADO_BIENESTAR=${URL_ESTADO_BIENESTAR}
      - CLIENT_NAME=${CLIENT_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} 
    ports:
      - "8080:8080"
    networks: 
      - teampulse
    restart: always
    depends_on: 
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks: 
      - teampulse
    volumes:
      - dbdata:/data/db

networks:
  teampulse:

volumes:
  dbdata:
